head = ../head/compiled/l2.html
s_head = ./spotlight_top.html
s_foot = ./spotlight_bottom.html
foot = ../footer/compiled/l2.html

all: biomedical fintech consulting

biomedical:
	cat $(head) $(s_head) ./biomedical_top.html $(s_foot) $(foot) > ../../spotlight/biomedical/index.html

fintech:
	cat $(head) $(s_head) ./fintech_top.html $(s_foot) $(foot) > ../../spotlight/fintech/index.html

consulting:
	cat $(head) $(s_head) ./consulting_top.html $(s_foot) $(foot) > ../../spotlight/consulting/index.html	