head = ../head/compiled/l1.html
foot = ../footer/compiled/l1.html

# Compile the questions and answers to the compiled folder and then copy the 
index.html:
	./compile-questions.sh && cat $(head) ./compiled/index.html $(foot) > ../../FAQ/index.html